# -*- coding: utf-8 -*-
"""ramayancontext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHaFPC1ZMMxYxaH1bpZ2irj5c2hexFAP
"""

!pip install transformers

from transformers import AutoTokenizer, AutoModelForQuestionAnswering, pipeline

# Load pre-trained tokenizer and model for question-answering
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-cased-distilled-squad")
model = AutoModelForQuestionAnswering.from_pretrained("distilbert-base-cased-distilled-squad")

# Define context and question
context = "RAM is the king of ayodhya, the kids of ram were lava kusa,son of dasaradh and kowsalaya were the parents of ram,wife of ram is seeta,ruled ayodhya for long time  ram age is 3000 years"
context1 = "ram married seeta and killed ravana."
context2 = "ram who is husband of seeta left her  and ruled ayodhya "
question = "What is kingdom ruled by ram"
question1 = "Who are lavakusa"
question2 = "who is seeta"
question3 = "What is the age of ram"

# Use pipeline to generate answer
nlp = pipeline('question-answering', model=model, tokenizer=tokenizer)
result = nlp(question=question, context=context)
result1 = nlp(question=question1, context=context)
result2 = nlp(question=question2, context=context)
result3 = nlp(question=question3, context=context)


# Print answer
print(result["answer"])
print(result1["answer"])
print(result2["answer"])
print(result3["answer"])